# -*- coding: utf-8 -*-
"""exercicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g04gF405odHts7luBOkEsyzQ6BrUqMy7
"""

import numpy as np

Lambda= 0.6 # Taxa de chegada
mu =1 # Taxa de servico
elemento_Fila = 0 #quantidade de carros na fila inicialmente
elemento_servidor = 1 #quantidade de carro no servico
K=0  ## Primeira iteracao ,
t=0  ## Tempo inicial
tc=t+np.random.exponential((1/Lambda)) # Tempo de chegada
tp=t+np.random.exponential((1/mu)) # Tempo de partida
t=min(tc,tp)
Tempo_chegada =[0]     # Armazena os tempos de chegada dos carros
Tempo_partida =[]      # Armazena os tempos de partida dos carros
Tq=[]     # tempo no medio que um elemento passa na fila

while t<pow(10,5):
    if tc<tp:  #  chegada de um novo carro
        Tempo_chegada=np.append(Tempo_chegada,t) # Armazena o tempo de chegada
        tc=t+np.random.exponential((1/Lambda))  #Gera um novo tempo de chegada e soma com t
        if elemento_servidor==1: # Se o servidor esta ocupado
            elemento_Fila=elemento_Fila+1  # coloca o carro na fila
        elif elemento_servidor==0: # Se o servidor esta desocupado?
            elemento_servidor=1  # Ocupa o servidor
            tp=t+np.random.exponential((1/mu)) # Gera novo tempo de partida
    elif tc>tp: # partida de um carro
        K=K+1
        Tempo_partida = np.append(Tempo_partida, t) #armazena o tempo da partida
        Tq = np.append(Tq, (Tempo_partida[K-1]-Tempo_chegada[K-1])) # calcula o tempo no sistema
        if elemento_Fila>0:
            elemento_Fila=elemento_Fila-1    # Decrementa um  carro da fila
            tp=t+np.random.exponential((1/mu)) # Gero um novo tempo de partida
            elemento_servidor=1  # Ocupar o servidor
        elif elemento_Fila==0: # se a fila esta vazia
            elemento_servidor=0 # Libera o serviodr
            tp=np.infty # Tempo de partida e infinito
    t=min(tc,tp) # Atualiza para o proximo evento

Ets=1/mu # Tempo medio de servico
Etq = np.mean(Tq) #Tempo medio no sistema
Eq=Lambda*Etq #Numero medio de elementos no sistema
Etw=Etq-Ets #Tempo medio de espera na fila
Ew=Lambda*Etw # Numero medio de elementos na fila



print(" O tempo médio dos carros no sistema (minuto) é: ", Etq )
print(" O número médio dos carros na fila é: ", Ew)